### ISSUE TITLE
backup restoreを使ってDBを複製する

### ISSUE THREAD

**Issue by uchicom** [uchicom/sqlv#10]
# GOAL
sql server2000のレプリカを作成する

# DESIGN
実行形式は引数を指定する。引数指定した場合はjob実行モードにする
java -jar Main -job job1
ymlにjobを定義しておいてジョブ名を実行すると、設定ファイルを使用して、jobを実行する。

## ファイル形式
config.yml
```
jobs:
  job1:
    tasks:
     - name:
       driver:
       jdbcUrl:
       username:
       password:
       sql:backup
     - name:
       driver:
       jdbcUrl:
       username:
       password:
       sql:restore
  job2:
```
