### ISSUE TITLE
add gitpod config

### ISSUE THREAD

**Issue by uchicom** [uchicom/sqlv#2]
.gitpod.yml
```
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
tasks:
  - init: 'echo export JAVA_TOOL_OPTIONS=\"$JAVA_TOOL_OPTIONS -Dsun.java2d.xrender=false\" >>/home/gitpod/.bashrc'
    command: 'source /home/gitpod/.bashrc'
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - donjayamanne.githistory
    - github.vscode-pull-request-github
```
